name: auto-build-deploy
run-name: ${{ github.actor }} is building and deploying
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{ secrets.CPART_HOST }}
        user: ${{ secrets.CPART_USER }}
        private_key: ${{ secrets.CPART_PRIVATE_KEY }}
        host_fingerprint: ${{ secrets.CPART_FINGERPRINT }}
        command: source ~/.nvm/nvm.sh; ~/deploy.sh
          