name: auto-build-deploy
run-name: ${{ github.actor }} is building and deploying
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"
    - run: npm ci
    - run: npm run build
    - run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@46.17.248.18.dev:/var/www/
